name: Format
on:
  pull_request:
    branches:
      - main
      - integration
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
            with:
              ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - run: npm install
      - run: npm ci
      - run: npm run format
      - name: Check for modified files
          id: git-check
          run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'github-actions' 
          git config --global user.email 'github-actions@github.com' 
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automated prettier fixes"
          git push